version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - 8000:9090
    volumes:
      - ./app:/app
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    
  