# Generated by Django 5.2.1 on 2025-06-03 05:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade da Proposta')),
                ('status', models.CharField(choices=[('NAO_ENVIADO', 'Não Enviado'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='NAO_ENVIADO', max_length=20, verbose_name='Status')),
                ('descricao_geral', models.TextField(blank=True, null=True, verbose_name='Descrição Geral/Observações do Orçamento')),
                ('total_produtos_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Custo Total Produtos')),
                ('total_produtos_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Venda Total Produtos')),
                ('total_mao_de_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Total Mão de Obra')),
                ('total_insumos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Total Insumos/Gastos Adicionais')),
                ('valor_total_orcamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Valor Total do Orçamento')),
                ('lucro_equipamentos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Lucro Equipamentos (Venda - Custo)')),
                ('lucro_total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Lucro Total Bruto (Venda Prod. + M.O. - Custo Prod.)')),
                ('lucro_total_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Lucro Total Líquido (Após Insumos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='customers.customer', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformacoesOrcamento',
            fields=[
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='informacoes_adicionais', serialize=False, to='quotes.orcamento', verbose_name='Orçamento')),
                ('condicoes_pagamento', models.TextField(blank=True, null=True, verbose_name='Condições de Pagamento')),
                ('prazo_entrega_instalacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prazo de Entrega/Instalação')),
                ('garantia', models.TextField(blank=True, null=True, verbose_name='Termos de Garantia')),
            ],
            options={
                'verbose_name': 'Informação Adicional do Orçamento',
                'verbose_name_plural': 'Informações Adicionais do Orçamento',
            },
        ),
        migrations.CreateModel(
            name='InsumoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Insumo/Gasto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do Insumo/Gasto')),
                ('data_gasto', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Gasto')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_orcamento', to='quotes.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Insumo/Gasto do Orçamento',
                'verbose_name_plural': 'Insumos/Gastos do Orçamento',
                'ordering': ['-data_gasto'],
            },
        ),
        migrations.CreateModel(
            name='MaoDeObraOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INSTALACAO', 'Instalação'), ('MANUTENCAO', 'Manutenção'), ('CONFIGURACAO', 'Configuração'), ('CONSULTORIA', 'Consultoria'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo de Serviço')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_mao_de_obra', to='quotes.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Item de Mão de Obra do Orçamento',
                'verbose_name_plural': 'Itens de Mão de Obra do Orçamento',
            },
        ),
        migrations.CreateModel(
            name='ItemProdutoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade')),
                ('preco_compra_unitario_historico', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Preço de Compra Unit. (Histórico)')),
                ('preco_venda_unitario_definido', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Preço de Venda Unit. (Definido)')),
                ('porcentagem_markup', models.DecimalField(blank=True, decimal_places=2, help_text='Se preenchido, calcula o preço de venda sobre o preço de compra. Ex: 20 para 20%.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Markup (%)')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produto', to='quotes.orcamento', verbose_name='Orçamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Produto do Orçamento',
                'verbose_name_plural': 'Itens de Produtos do Orçamento',
                'unique_together': {('orcamento', 'produto')},
            },
        ),
    ]
