# Generated by Django 5.2.1 on 2025-06-02 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo / Razão Social')),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('OUTRO', 'Outro')], default='CPF', max_length=5, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Documento (CPF/CNPJ)')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='E-mail Principal')),
                ('tipo_cliente', models.CharField(choices=[('COMODATO', 'Comodato'), ('CONTRATO', 'Contrato'), ('AVULSO', 'Avulso')], default='AVULSO', max_length=10, verbose_name='Tipo de Cliente')),
                ('endereco_logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('endereco_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('endereco_complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('endereco_bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('endereco_cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('endereco_estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('endereco_cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('criar_usuario_sistema', models.BooleanField(default=False, verbose_name='Criar acesso ao sistema para este cliente?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario_sistema', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Acesso do Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
