# Generated by Django 5.2.1 on 2025-06-11 15:59

import apps.servicedesk.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0002_remove_ticket_category_remove_ticket_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='servicedesk.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria'),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentário / Atividade')),
                ('comment_type', models.CharField(choices=[('COMMENT', 'Comentário'), ('LOG', 'Registo de Atividade')], default='COMMENT', max_length=10, verbose_name='Tipo')),
                ('is_internal_note', models.BooleanField(default=False, help_text='Notas internas são visíveis apenas para a equipa.', verbose_name='É uma nota interna?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, help_text='Se nulo, é um registo do sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='servicedesk.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Comentário de Ticket',
                'verbose_name_plural': 'Comentários de Tickets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.servicedesk.models.ticket_attachment_path, verbose_name='Ficheiro')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='servicedesk.ticketcomment', verbose_name='Comentário Associado')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
