# Generated by Django 5.2.1 on 2025-06-13 00:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_produto_quantidade_em_estoque'),
        ('quotes', '0001_initial'),
        ('servicedesk', '0003_alter_category_options_ticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='orcamento_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_de_servico_geradas', to='quotes.orcamento', verbose_name='Orçamento de Origem'),
        ),
        migrations.CreateModel(
            name='ProdutoUtilizadoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade Utilizada')),
                ('preco_compra_no_momento', models.DecimalField(decimal_places=2, help_text='Custo do produto no momento em que foi adicionado à OS.', max_digits=16)),
                ('preco_venda_no_momento', models.DecimalField(decimal_places=2, help_text='Preço de venda praticado no momento.', max_digits=16)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('ordem_de_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_utilizados', to='servicedesk.workorder', verbose_name='Ordem de Serviço')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilizado_em_os', to='inventory.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto Utilizado em OS',
                'verbose_name_plural': 'Produtos Utilizados em OS',
                'unique_together': {('ordem_de_servico', 'produto')},
            },
        ),
    ]
